### PR TITLE
change ' to "

### PR DESCRIPTION
**Pull request by 7ym0n**
formatter style, it's not work..

### CODE REVIEW

**Comment by Artawower** [comment]
I have been updated readme. You can use customize your own configuration without modification package configs
```
(setcdr (assq 'typescript-mode turbo-log-loggers)
        '((:loggers ("console.log(%s)" "console.debug(%s)" "console.warn(%s)")
           :jump-list ((class_declaration (method_definition "constructor")))
           :msg-format-template "\"TCL: %s\""
           :identifier-node-types (identifier member_expression)
           :post-insert-hook (prettier-prettify))))
```
Or are you trying to solve another problem?

**Comment by 7ym0n** [comment]
> I have been updated readme. You can use customize your own configuration without modification package configs
> 
> ```
> (setcdr (assq 'typescript-mode turbo-log-loggers)
>         '((:loggers ("console.log(%s)" "console.debug(%s)" "console.warn(%s)")
>            :jump-list ((class_declaration (method_definition "constructor")))
>            :msg-format-template "\"TCL: %s\""
>            :identifier-node-types (identifier member_expression)
>            :post-insert-hook (prettier-prettify))))
> ```
> 
> Or are you trying to solve another problem?

I tried your said config， I settings it,  There are too many duplicate codes.
```
(let ((config '((:loggers ("console.log(%s)" "console.debug(%s)" "console.warn(%s)")
                   :jump-list ((class_declaration (method_definition "constructor")))
                   :msg-format-template "\"TCL: %s\""
                   :identifier-node-types (identifier member_expression)
                   :post-insert-hook (prettier-prettify)))))
    (setcdr (assq 'js-mode turbo-log-loggers)
            config)
    (setcdr (assq 'typescript-mode turbo-log-loggers)
            config)
    (setcdr (assq 'rjsx-mode turbo-log-loggers)
            config)
    (setcdr (assq 'js2-mode turbo-log-loggers)
            config)
    (setcdr (assq 'web-mode turbo-log-loggers)
            config))
```

**Comment by Artawower** [comment]
Okay, I see your point now. But that's not the answer, because some people may want to use a different config and they will have to use such a redundant approach to configure ecmascript-based languages. I'll think about macros for a simple configuration with a merge strategy. For now you can use a loop over a list of characters:
```
(dolist (mode '(typescript-mode js-mode web-mode))

  (setcdr (assq mode turbo-log-loggers)
          config))
```
I will try to create macros this weekend.

**Comment by 7ym0n** [comment]
> (dolist (mode '(typescript-mode js-mode web-mode))
> 
>   (setcdr (assq mode turbo-log-loggers)
>           config))

ok!
good job.

**Comment by Artawower** [comment]
I added a new macro to simplify logger setup, you can try it in the last commit

```
(turbo-log-configure
 :modes (typescript-mode js2-mode web-mode other-modes)
 :strategy merge

 ;; ... Other possible configs 
 :msg-format-template "\"🦄: %s\"")
```

**Pull request closed without merging**
